title: "Konstantine Razmadze"
author: "Konstantine Razmadze"
description: "TSU/LMU (MCMP)"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true           # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header


# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}         

  - {title: "Talks and Conferences", file: "Talks and Conferences.md"}
  - {title: "Projects", file: "Projects.md"}
  - {title: "CV", url: "/CV.pdf.pdf", target: "_blank"}
  - {title: "Contacts", file: "contacts.md"}



external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:k.razmadze92@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/konstantinerazmadze"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Konstantine-Razmadze?ev=hdr_xprf"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
